export const tableFirstData = {
  firstName: 'Gianni',
  lastName: 'Morandi',
  address: 'Via Roma, 1, Treno',
  uid: 3456789542556789,
  info: 123123.12,
};

export const tableData = [
  {
    ...tableFirstData,
    subRows: [
      {
        firstName: 'ciao',
        lastName: 'Stuffo',
        address: 'Via Roma, 15 Monza',
        uid: 123123,
        info: 12,
        subRows: [
          {
            firstName: '1',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
            subRows: [
              {
                firstName: '1',
                lastName: 'Stuffo',
                address: 'Via Roma, 15 Monza',
                uid: 123123,
                info: 12,
                subRows: [
                  {
                    firstName: '1',
                    lastName: 'Stuffo',
                    address: 'Via Roma, 15 Monza',
                    uid: 123123,
                    info: 12,
                    subRows: [
                      {
                        firstName: '1',
                        lastName: 'Stuffo',
                        address: 'Via Roma, 15 Monza',
                        uid: 123123,
                        info: 12,
                        subRows: [
                          {
                            firstName: '1',
                            lastName: 'Stuffo',
                            address: 'Via Roma, 15 Monza',
                            uid: 123123,
                            info: 12,
                            subRows: [
                              {
                                firstName: '1',
                                lastName: 'Stuffo',
                                address: 'Via Roma, 15 Monza',
                                uid: 123123,
                                info: 12,
                                subRows: [
                                  {
                                    firstName: '1',
                                    lastName: 'Stuffo',
                                    address: 'Via Roma, 15 Monza',
                                    uid: 123123,
                                    info: 12,
                                    subRows: [
                                      {
                                        firstName: '1',
                                        lastName: 'Stuffo',
                                        address: 'Via Roma, 15 Monza',
                                        uid: 123123,
                                        info: 12,
                                      },
                                      {
                                        firstName: '2',
                                        lastName: 'Stuffo',
                                        address: 'Via Roma, 15 Monza',
                                        uid: 123123,
                                        info: 12,
                                      },
                                      {
                                        firstName: '3',
                                        lastName: 'Stuffo',
                                        address: 'Via Roma, 15 Monza',
                                        uid: 123123,
                                        info: 12,
                                      },
                                    ],
                                  },
                                  {
                                    firstName: '2',
                                    lastName: 'Stuffo',
                                    address: 'Via Roma, 15 Monza',
                                    uid: 123123,
                                    info: 12,
                                  },
                                  {
                                    firstName: '3',
                                    lastName: 'Stuffo',
                                    address: 'Via Roma, 15 Monza',
                                    uid: 123123,
                                    info: 12,
                                  },
                                ],
                              },
                              {
                                firstName: '2',
                                lastName: 'Stuffo',
                                address: 'Via Roma, 15 Monza',
                                uid: 123123,
                                info: 12,
                              },
                              {
                                firstName: '3',
                                lastName: 'Stuffo',
                                address: 'Via Roma, 15 Monza',
                                uid: 123123,
                                info: 12,
                              },
                            ],
                          },
                          {
                            firstName: '2',
                            lastName: 'Stuffo',
                            address: 'Via Roma, 15 Monza',
                            uid: 123123,
                            info: 12,
                          },
                          {
                            firstName: '3',
                            lastName: 'Stuffo',
                            address: 'Via Roma, 15 Monza',
                            uid: 123123,
                            info: 12,
                          },
                        ],
                      },
                      {
                        firstName: '2',
                        lastName: 'Stuffo',
                        address: 'Via Roma, 15 Monza',
                        uid: 123123,
                        info: 12,
                      },
                      {
                        firstName: '3',
                        lastName: 'Stuffo',
                        address: 'Via Roma, 15 Monza',
                        uid: 123123,
                        info: 12,
                      },
                    ],
                  },
                  {
                    firstName: '2',
                    lastName: 'Stuffo',
                    address: 'Via Roma, 15 Monza',
                    uid: 123123,
                    info: 12,
                  },
                  {
                    firstName: '3',
                    lastName: 'Stuffo',
                    address: 'Via Roma, 15 Monza',
                    uid: 123123,
                    info: 12,
                  },
                ],
              },
              {
                firstName: '2',
                lastName: 'Stuffo',
                address: 'Via Roma, 15 Monza',
                uid: 123123,
                info: 12,
              },
              {
                firstName: '3',
                lastName: 'Stuffo',
                address: 'Via Roma, 15 Monza',
                uid: 123123,
                info: 12,
              },
            ],
          },
          {
            firstName: '2',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
          },
          {
            firstName: '3',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
          },
        ],
      },
    ],
  },
  {
    firstName: 'Simone',
    lastName: 'Lastname',
    address: 'Via Roma, 12, Bologna',
    uid: '345367890',
    canBeDeleted: true,
    info: 123.96,
  },
  {
    firstName: 'Matteo',
    lastName: 'Staffone',
    address: 'Via Roma, 13, Genova',
    uid: 23456789,
    info: <code>23456789</code>,
    subRows: [
      {
        firstName: '1',
        lastName: 'Stuffo',
        address: 'Via Roma, 15 Monza',
        uid: 123123,
        info: 12,
      },
      {
        firstName: '2',
        lastName: 'Stuffo',
        address: 'Via Roma, 15 Monza',
        uid: 123123,
        info: 12,
        subRows: [
          {
            firstName: '1',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
            subRows: [
              {
                firstName: '1',
                lastName: 'Stuffo',
                address: 'Via Roma, 15 Monza',
                uid: 123123,
                info: 12,
              },
              {
                firstName: '2',
                lastName: 'Stuffo',
                address: 'Via Roma, 15 Monza',
                uid: 123123,
                info: 12,
              },
              {
                firstName: '3',
                lastName: 'Stuffo',
                address: 'Via Roma, 15 Monza',
                uid: 123123,
                info: 12,
              },
            ],
          },
          {
            firstName: '2',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
          },
          {
            firstName: '3',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
          },
        ],
      },
      {
        firstName: '3',
        lastName: 'Stuffo',
        address: 'Via Roma, 15 Monza',
        uid: 123123,
        info: 12,
        subRows: [
          {
            firstName: '1',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
          },
          {
            firstName: '2',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
          },
          {
            firstName: '3',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
          },
        ],
      },
    ],
  },
  {
    firstName: 'Emanuele',
    lastName: 'Staffo',
    address: 'Via Roma, 14, Milano',
    uid: '2345678',
    info: 1234,
  },
  {
    firstName: 'Simone',
    lastName: 'Stuffo',
    address: 'Via Roma, 15 Monza',
    uid: 123123,
    info: 12,
    subRows: [
      {
        firstName: 'ciao',
        lastName: 'Stuffo',
        address: 'Via Roma, 15 Monza',
        uid: 123123,
        info: 12,
      },
    ],
  },
  {
    firstName: 'Luca',
    lastName: 'Morandi',
    address: 'Via Roma, 1, Treno',
    uid: 3456795423556789,
    info: 123123.12,
    subRows: [
      {
        firstName: 'ciao',
        lastName: 'Stuffo',
        address: 'Via Roma, 15 Monza',
        uid: 123123,
        info: 12,
      },
    ],
  },
  {
    firstName: 'Mattia',
    lastName: 'Lastname',
    address: 'Via Roma, 12, Bologna',
    uid: 345367890,
    info: 123.96,
  },
  {
    firstName: 'Morfeo',
    lastName: 'Staffone',
    address: 'Via Roma, 13, Genova',
    uid: 3434235,
    info: 12.1213,
  },
  {
    firstName: 'Gianluca',
    lastName: 'Staffo',
    address: 'Via Roma, 14, Milano',
    uid: 2345678,
    info: 1234,
  },
  {
    firstName: 'Simone',
    lastName: 'Stuffo',
    address: 'Via Roma, 15 Monza',
    uid: 123123,
    info: 12,
  },
  {
    firstName: 'Simone',
    lastName: 'Stuffo',
    address: 'Via Roma, 15 Monza',
    uid: 123123,
    info: 12,
  },
  {
    firstName: 'Simone',
    lastName: 'Stuffo',
    address: 'Via Roma, 15 Monza',
    uid: 123123,
    info: 12,
  },
  {
    firstName: 'Simone',
    lastName: 'Stuffo',
    address: 'Via Roma, 15 Monza',
    uid: 123123,
    info: 12,
  },
  {
    firstName: 'Simone',
    lastName: 'Stuffo',
    address: 'Via Roma, 15 Monza',
    uid: 123123,
    info: 12,
  },
  {
    firstName: 'Simone',
    lastName: 'Stuffo',
    address: 'Via Roma, 15 Monza',
    uid: 123123,
    info: 12,
  },
  {
    firstName: 'Simone',
    lastName: 'Stuffo',
    address: 'Via Roma, 15 Monza',
    uid: 123123,
    info: 12,
  },
];

export const tableDataWithIds = [
  {
    ...tableFirstData,
    subRows: [
      {
        _id: '1.1',
        firstName: 'ciao',
        lastName: 'Stuffo',
        address: 'Via Roma, 15 Monza',
        uid: 123123,
        info: 12,
        subRows: [
          {
            _id: '1.1.1',
            firstName: '1',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
            subRows: [
              {
                _id: '1.1.1.1',
                firstName: '1',
                lastName: 'Stuffo',
                address: 'Via Roma, 15 Monza',
                uid: 123123,
                info: 12,
                subRows: [
                  {
                    _id: '1.1.1.1.1',
                    firstName: '1',
                    lastName: 'Stuffo',
                    address: 'Via Roma, 15 Monza',
                    uid: 123123,
                    info: 12,
                    subRows: [
                      {
                        _id: '1.1.1.1.1.1',
                        firstName: '1',
                        lastName: 'Stuffo',
                        address: 'Via Roma, 15 Monza',
                        uid: 123123,
                        info: 12,
                        subRows: [
                          {
                            _id: '1.1.1.1.1.1.1',
                            firstName: '1',
                            lastName: 'Stuffo',
                            address: 'Via Roma, 15 Monza',
                            uid: 123123,
                            info: 12,
                            subRows: [
                              {
                                _id: '1.1.1.1.1.1.1.1',
                                firstName: '1',
                                lastName: 'Stuffo',
                                address: 'Via Roma, 15 Monza',
                                uid: 123123,
                                info: 12,
                                subRows: [
                                  {
                                    _id: '1.1.1.1.1.1.1.1.1',
                                    firstName: '1',
                                    lastName: 'Stuffo',
                                    address: 'Via Roma, 15 Monza',
                                    uid: 123123,
                                    info: 12,
                                    subRows: [
                                      {
                                        _id: '1.1.1.1.1.1.1.1.1.1',
                                        firstName: '1',
                                        lastName: 'Stuffo',
                                        address: 'Via Roma, 15 Monza',
                                        uid: 123123,
                                        info: 12,
                                      },
                                      {
                                        _id: '1.1.1.1.1.1.1.1.1.2',
                                        firstName: '2',
                                        lastName: 'Stuffo',
                                        address: 'Via Roma, 15 Monza',
                                        uid: 123123,
                                        info: 12,
                                      },
                                      {
                                        _id: '1.1.1.1.1.1.1.1.1.3',
                                        firstName: '3',
                                        lastName: 'Stuffo',
                                        address: 'Via Roma, 15 Monza',
                                        uid: 123123,
                                        info: 12,
                                      },
                                    ],
                                  },
                                  {
                                    _id: '1.1.1.1.1.1.1.1.2',
                                    firstName: '2',
                                    lastName: 'Stuffo',
                                    address: 'Via Roma, 15 Monza',
                                    uid: 123123,
                                    info: 12,
                                  },
                                  {
                                    _id: '1.1.1.1.1.1.1.1.3',
                                    firstName: '3',
                                    lastName: 'Stuffo',
                                    address: 'Via Roma, 15 Monza',
                                    uid: 123123,
                                    info: 12,
                                  },
                                ],
                              },
                              {
                                _id: '1.1.1.1.1.1.1.2',
                                firstName: '2',
                                lastName: 'Stuffo',
                                address: 'Via Roma, 15 Monza',
                                uid: 123123,
                                info: 12,
                              },
                              {
                                _id: '1.1.1.1.1.1.1.3',
                                firstName: '3',
                                lastName: 'Stuffo',
                                address: 'Via Roma, 15 Monza',
                                uid: 123123,
                                info: 12,
                              },
                            ],
                          },
                          {
                            _id: '1.1.1.1.1.1.2',
                            firstName: '2',
                            lastName: 'Stuffo',
                            address: 'Via Roma, 15 Monza',
                            uid: 123123,
                            info: 12,
                          },
                          {
                            _id: '1.1.1.1.1.1.3',
                            firstName: '3',
                            lastName: 'Stuffo',
                            address: 'Via Roma, 15 Monza',
                            uid: 123123,
                            info: 12,
                          },
                        ],
                      },
                      {
                        _id: '1.1.1.1.1.2',
                        firstName: '2',
                        lastName: 'Stuffo',
                        address: 'Via Roma, 15 Monza',
                        uid: 123123,
                        info: 12,
                      },
                      {
                        _id: '1.1.1.1.1.3',
                        firstName: '3',
                        lastName: 'Stuffo',
                        address: 'Via Roma, 15 Monza',
                        uid: 123123,
                        info: 12,
                      },
                    ],
                  },
                  {
                    _id: '1.1.1.1.2',
                    firstName: '2',
                    lastName: 'Stuffo',
                    address: 'Via Roma, 15 Monza',
                    uid: 123123,
                    info: 12,
                  },
                  {
                    _id: '1.1.1.1.3',
                    firstName: '3',
                    lastName: 'Stuffo',
                    address: 'Via Roma, 15 Monza',
                    uid: 123123,
                    info: 12,
                  },
                ],
              },
              {
                _id: '1.1.1.2',
                firstName: '2',
                lastName: 'Stuffo',
                address: 'Via Roma, 15 Monza',
                uid: 123123,
                info: 12,
              },
              {
                _id: '1.1.1.3',
                firstName: '3',
                lastName: 'Stuffo',
                address: 'Via Roma, 15 Monza',
                uid: 123123,
                info: 12,
              },
            ],
          },
          {
            _id: '1.1.2',
            firstName: '2',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
          },
          {
            _id: '1.1.3',
            firstName: '3',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
          },
        ],
      },
    ],
  },
  {
    _id: '2',
    firstName: 'Simone',
    lastName: 'Lastname',
    address: 'Via Roma, 12, Bologna',
    uid: '345367890',
    canBeDeleted: true,
    info: 123.96,
  },
  {
    _id: '3',
    firstName: 'Matteo',
    lastName: 'Staffone',
    address: 'Via Roma, 13, Genova',
    uid: 23456789,
    info: <code>23456789</code>,
    subRows: [
      {
        _id: '3.1',
        firstName: '1',
        lastName: 'Stuffo',
        address: 'Via Roma, 15 Monza',
        uid: 123123,
        info: 12,
      },
      {
        _id: '3.2',
        firstName: '2',
        lastName: 'Stuffo',
        address: 'Via Roma, 15 Monza',
        uid: 123123,
        info: 12,
        subRows: [
          {
            _id: '3.2.1',
            firstName: '1',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
            subRows: [
              {
                _id: '3.2.1.1',
                firstName: '1',
                lastName: 'Stuffo',
                address: 'Via Roma, 15 Monza',
                uid: 123123,
                info: 12,
              },
              {
                _id: '3.2.1.2',
                firstName: '2',
                lastName: 'Stuffo',
                address: 'Via Roma, 15 Monza',
                uid: 123123,
                info: 12,
              },
              {
                _id: '3.2.1.3',
                firstName: '3',
                lastName: 'Stuffo',
                address: 'Via Roma, 15 Monza',
                uid: 123123,
                info: 12,
              },
            ],
          },
          {
            _id: '3.2.2',
            firstName: '2',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
          },
          {
            _id: '3.2.3',
            firstName: '3',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
          },
        ],
      },
      {
        _id: '3.3',
        firstName: '3',
        lastName: 'Stuffo',
        address: 'Via Roma, 15 Monza',
        uid: 123123,
        info: 12,
        subRows: [
          {
            _id: '3.3.1',
            firstName: '1',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
          },
          {
            _id: '3.3.2',
            firstName: '2',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
          },
          {
            _id: '3.3.3',
            firstName: '3',
            lastName: 'Stuffo',
            address: 'Via Roma, 15 Monza',
            uid: 123123,
            info: 12,
          },
        ],
      },
    ],
  },
  {
    _id: '4',
    firstName: 'Emanuele',
    lastName: 'Staffo',
    address: 'Via Roma, 14, Milano',
    uid: '2345678',
    info: 1234,
  },
  {
    _id: '5',
    firstName: 'Simone',
    lastName: 'Stuffo',
    address: 'Via Roma, 15 Monza',
    uid: 123123,
    info: 12,
    subRows: [
      {
        _id: '5.1',
        firstName: 'ciao',
        lastName: 'Stuffo',
        address: 'Via Roma, 15 Monza',
        uid: 123123,
        info: 12,
      },
    ],
  },
  {
    _id: '6',
    firstName: 'Luca',
    lastName: 'Morandi',
    address: 'Via Roma, 1, Treno',
    uid: 3456795423556789,
    info: 123123.12,
    subRows: [
      {
        _id: '6.1',
        firstName: 'ciao',
        lastName: 'Stuffo',
        address: 'Via Roma, 15 Monza',
        uid: 123123,
        info: 12,
      },
    ],
  },
  {
    _id: '7',
    firstName: 'Mattia',
    lastName: 'Lastname',
    address: 'Via Roma, 12, Bologna',
    uid: 345367890,
    info: 123.96,
  },
  {
    _id: '8',
    firstName: 'Morfeo',
    lastName: 'Staffone',
    address: 'Via Roma, 13, Genova',
    uid: 3434235,
    info: 12.1213,
  },
  {
    _id: '9',
    firstName: 'Gianluca',
    lastName: 'Staffo',
    address: 'Via Roma, 14, Milano',
    uid: 2345678,
    info: 1234,
  },
  {
    _id: '10',
    firstName: 'Simone',
    lastName: 'Stuffo',
    address: 'Via Roma, 15 Monza',
    uid: 123123,
    info: 12,
  },
  {
    _id: '11',
    firstName: 'Simone',
    lastName: 'Stuffo',
    address: 'Via Roma, 15 Monza',
    uid: 123123,
    info: 12,
  },
  {
    _id: '12',
    firstName: 'Simone',
    lastName: 'Stuffo',
    address: 'Via Roma, 15 Monza',
    uid: 123123,
    info: 12,
  },
  {
    _id: '13',
    firstName: 'Simone',
    lastName: 'Stuffo',
    address: 'Via Roma, 15 Monza',
    uid: 123123,
    info: 12,
  },
  {
    _id: '14',
    firstName: 'Simone',
    lastName: 'Stuffo',
    address: 'Via Roma, 15 Monza',
    uid: 123123,
    info: 12,
  },
  {
    _id: '15',
    firstName: 'Simone',
    lastName: 'Stuffo',
    address: 'Via Roma, 15 Monza',
    uid: 123123,
    info: 12,
  },
  {
    _id: '16',
    firstName: 'Simone',
    lastName: 'Stuffo',
    address: 'Via Roma, 15 Monza',
    uid: 123123,
    info: 12,
  },
];
