name: Continuous Integration

on:
  pull_request:
    branches:
      - main

# Cancel in-progress jobs or runs for the current workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: lualtek/workflows/.github/workflows/ui_ci.yml@master
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
