name: Build, Release and Stage

on:
  push:
    branches:
      - main
      - 'next/*'

# Cancel in-progress jobs or runs for the current workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: lualtek/workflows/.github/workflows/ui_ci.yml@master
    secrets:
      RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      LUALTEK_RELEASE_APP_ID: ${{ secrets.LUALTEK_RELEASE_APP_ID }}
      LUALTEK_RELEASE_APP_PRIVATE_KEY: ${{ secrets.LUALTEK_RELEASE_APP_PRIVATE_KEY }}
    with:
      release: true
